# For more information: https://laravel.com/docs/fpm
version: '3'
services:
    laravel.dev:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                # WWWGROUP: "1001"
                WWWGROUP: '${WWWGROUP}'
        # image: app-cli:latest
        image: jn
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_FPM: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - fpm
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'fpmmysql:/var/lib/mysql'
        networks:
            - fpm
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s
networks:
    fpm:
        driver: bridge
volumes:
    fpmmysql:
        driver: local
    fpmredis:
        driver: local
    fpmmeilisearch:
        driver: local
